# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pgk4hE-cXYf4_l4rNIQ4kEljwN7y9Yr
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# --- 1. THE "REAL-WORLD" DATA GENERATOR ---

def generate_challenging_50hz(n_samples=1200, fs=4000, duration=0.2):
    t = np.linspace(0, duration, int(fs * duration))
    X, y = [], []

    for _ in range(n_samples):
        is_fault = np.random.choice([0, 1])

        # A. Frequency Jitter: The grid varies between 49.9 and 50.1 Hz
        actual_freq = np.random.uniform(49.9, 50.1)
        i_peak = np.random.uniform(10, 50)

        # B. Base Signal with Harmonics (Applied to BOTH classes)
        # 3rd and 5th harmonics are common in ALL modern power systems
        signal = i_peak * np.sin(2 * np.pi * actual_freq * t)
        signal += (i_peak * np.random.uniform(0.02, 0.12)) * np.sin(2 * np.pi * (3 * actual_freq) * t)
        signal += (i_peak * np.random.uniform(0.01, 0.05)) * np.sin(2 * np.pi * (5 * actual_freq) * t)

        if is_fault:
            # C. HIF Logic (Arcing)
            v_peak = 325
            v = v_peak * np.sin(2 * np.pi * actual_freq * t)
            v_ign = np.random.uniform(180, 270)
            v_burn = np.random.uniform(100, 140)

            # The current only flows when voltage exceeds ignition
            hif_signal = np.where(v > v_ign, (v - v_burn),
                         np.where(v < -v_ign, (v + v_burn), 0))
            # Scale HIF to be a fraction of the load current (hard to see!)
            signal = signal + (hif_signal * np.random.uniform(0.05, 0.15))
            y.append(1)
        else:
            # D. Non-Linear Normal Load (The "Trap")
            # Mimics LED drivers or dimmers that also have "dead zones"
            v = 325 * np.sin(2 * np.pi * actual_freq * t)
            dead_zone_v = np.random.uniform(30, 80)
            signal = np.where(np.abs(v) > dead_zone_v, signal, 0)
            y.append(0)

        # E. Noise & Phase Shift
        # Adding "White Noise" that is 5-10% of the signal peak
        noise = np.random.normal(0, np.max(np.abs(signal)) * np.random.uniform(0.05, 0.1), len(signal))
        signal += noise

        # Randomly roll the signal so the fault doesn't always start at t=0
        signal = np.roll(signal, np.random.randint(0, len(t)))

        X.append(signal)

    return np.array(X), np.array(y)

# --- 2. PRE-PROCESSING ---

print("Generating Challenging 50Hz Dataset...")
X_raw, y_raw = generate_challenging_50hz()

# Reshape for LSTM (Samples, Time_Steps, 1)
X = X_raw.reshape((X_raw.shape[0], X_raw.shape[1], 1))

# Z-Score Normalization (Standardization)
# This is much harder for the model than simple 0-1 scaling
X = (X - np.mean(X, axis=1, keepdims=True)) / np.std(X, axis=1, keepdims=True)

X_train, X_test, y_train, y_test = train_test_split(X, y_raw, test_size=0.2, shuffle=True)

# --- 3. THE LSTM ARCHITECTURE ---

model = Sequential([
    # Reduced capacity to prevent "overfitting" on synthetic math
    LSTM(32, input_shape=(X.shape[1], 1), return_sequences=True),
    BatchNormalization(),
    Dropout(0.4),

    LSTM(16),
    Dropout(0.4),

    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Using a slower learning rate to force the model to look for deeper features
opt = tf.keras.optimizers.Adam(learning_rate=0.0005)
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

# --- 4. TRAINING & EVALUATION ---

print("\nStarting Training.............")
history = model.fit(X_train, y_train,
                    epochs=30,
                    batch_size=32,
                    validation_data=(X_test, y_test),
                    verbose=1)

# Final Diagnostics
y_pred = (model.predict(X_test) > 0.5).astype(int)
print("\n--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))
print("\n--- Final Report ---")
print(classification_report(y_test, y_pred))